// src/components/mtb/ItemList.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import { tweened } from 'svelte/motion'
  import { fly } from 'svelte/transition'
  import ItemEntry from './ItemEntry.svelte'
  import type { Category } from '@/types'
  import { isMobile } from '@/hooks/isMobile.svelte'
  import { t } from '@/lib/i18n.svelte'
  import { cubicBezier } from '@/lib/utils'

  // Matches the pre-migration Motion `animate(scrollY, target, { duration: 0.3, ease: [0.25, 1, 0.5, 1] })`
  const EASE = cubicBezier(0.25, 1, 0.5, 1)

  interface Props {
    category: Category
    activeItemIndex: number
    onSelectItem: (index: number) => void
    onOpenItem: (index: number) => void
  }

  let {
    category,
    activeItemIndex,
    onSelectItem,
    onOpenItem,
  }: Props = $props()

  const ROW_PITCH = $derived(isMobile() ? 72 : 96)
  const FALLOFF = $derived(isMobile() ? 130 : 180)

  // Tweened scroll offset initialized using untrack to prevent reactive capture warning
  const scrollY = tweened(untrack(() => -activeItemIndex * (isMobile() ? 72 : 96)), { duration: 300, easing: EASE })

  $effect(() => {
    scrollY.set(-activeItemIndex * ROW_PITCH)
  })

  function resolveItemVisuals(dy: number, rowPitch: number, falloff: number) {
    const adyF = Math.abs(dy) / falloff
    const adyR = Math.abs(dy) / rowPitch
    const scale = Math.abs(dy) >= falloff ? 0.8 : 0.8 + (1 - adyF ** 2) * 0.2
    const opacity =
      dy < 0
        ? Math.abs(dy) >= rowPitch ? 0 : 1 - adyR ** 2
        : Math.abs(dy) >= falloff ? 0.4 : 0.4 + (1 - adyF ** 2) * 0.6
    const subOpacity = Math.abs(dy) >= falloff ? 0 : (1 - adyF ** 2) ** 2
    return { scale, opacity, subOpacity }
  }
</script>

{#if category.items.length === 0}
  <div
    class="px-8 py-4 col-start-1 row-start-1"
    in:fly={{ x: 20, duration: 300, easing: EASE }}
    out:fly={{ x: -20, duration: 300, easing: EASE }}
  >
    <p class="text-sm text-[var(--text-muted)] font-mono">{t('apps.loading')}</p>
  </div>
{:else}
  <div
    role="listbox"
    class="w-full flex flex-col gap-1 col-start-1 row-start-1"
    style:transform="translateY({$scrollY}px)"
    in:fly={{ x: 20, duration: 300, easing: EASE }}
    out:fly={{ x: -20, duration: 300, easing: EASE }}
  >
    {#each category.items as item, i (item.id)}
      {@const dy = i * ROW_PITCH + $scrollY}
      {@const { scale, opacity, subOpacity } = resolveItemVisuals(dy, ROW_PITCH, FALLOFF)}

      <div class="w-full shrink-0 origin-left">
        <ItemEntry
          {item}
          isActive={i === activeItemIndex}
          {opacity}
          {scale}
          {subOpacity}
          onclick={() => {
            if (i === activeItemIndex) {
              onOpenItem(i)
            } else {
              onSelectItem(i)
            }
          }}
        />
      </div>
    {/each}
  </div>
{/if}

// src/components/mtb/ItemList.tsx
import { useEffect } from 'react'
import { AnimatePresence, motion, useMotionValue, useTransform, animate, type MotionValue } from 'motion/react'
import { useTranslation } from 'react-i18next'
import { ItemEntry } from './ItemEntry'
import type { Category, MTBItem } from '@/types'
import { useIsMobile } from '@/hooks/useIsMobile'

interface Props {
  category: Category
  activeItemIndex: number
  onSelectItem: (index: number) => void
  onOpenItem: (index: number) => void
}

interface ItemWrapperProps {
  item: MTBItem
  index: number
  activeItemIndex: number
  scrollY: MotionValue<number>
  onSelectItem: (index: number) => void
  onOpenItem: (index: number) => void
}

function PlaylistItemWrapper({
  item,
  index,
  activeItemIndex,
  scrollY,
  onSelectItem,
  onOpenItem,
}: ItemWrapperProps) {
  const isMobile = useIsMobile()
  const ROW_PITCH = isMobile ? 72 : 96
  const FALLOFF = isMobile ? 130 : 180

  // Distance from the center of the fixed selection rail.
  const scale = useTransform(scrollY, (y) => {
    const dy = index * ROW_PITCH + y
    const absDy = Math.abs(dy)
    if (absDy >= FALLOFF) return 0.8
    const t = absDy / FALLOFF
    const factor = 1 - t * t // smooth ease-out quadratic
    return 0.8 + factor * 0.2 // scales from 0.8 to 1.0
  })

  const opacity = useTransform(scrollY, (y) => {
    const dy = index * ROW_PITCH + y
    if (dy < 0) {
      // Items scrolling up past the selection line: steep falloff to 0 to prevent overlap
      const absDy = Math.abs(dy)
      if (absDy >= ROW_PITCH) return 0
      const t = absDy / ROW_PITCH
      return 1 - t * t // fades to 0 one step up
    } else {
      // Items scrolling down below the selection line: standard falloff to 0.4
      const absDy = Math.abs(dy)
      if (absDy >= FALLOFF) return 0.4
      const t = absDy / FALLOFF
      const factor = 1 - t * t
      return 0.4 + factor * 0.6
    }
  })

  const subOpacity = useTransform(scrollY, (y) => {
    const dy = index * ROW_PITCH + y
    const absDy = Math.abs(dy)
    if (absDy >= FALLOFF) return 0
    const t = absDy / FALLOFF
    const factor = 1 - t * t
    return factor * factor // steeper falloff for subtitles
  })

  return (
    <motion.div
      style={{
        opacity,
        scale,
      }}
      className="w-full shrink-0 origin-left"
    >
      <ItemEntry
        item={item}
        isActive={index === activeItemIndex}
        subOpacity={subOpacity}
        onClick={() => {
          if (index === activeItemIndex) {
            onOpenItem(index)
          } else {
            onSelectItem(index)
          }
        }}
      />
    </motion.div>
  )
}

export function ItemList({ category, activeItemIndex, onSelectItem, onOpenItem }: Props) {
  const { t } = useTranslation()
  const isMobile = useIsMobile()
  const ROW_PITCH = isMobile ? 72 : 96
  const scrollY = useMotionValue(-activeItemIndex * ROW_PITCH)

  useEffect(() => {
    animate(scrollY, -activeItemIndex * ROW_PITCH, {
      duration: 0.3,
      ease: [0.25, 1, 0.5, 1],
    })
  }, [activeItemIndex, scrollY, ROW_PITCH])

  if (category.items.length === 0) {
    return (
      <div className="px-8 py-4">
        <p className="text-sm text-[var(--text-muted)]">{t('apps.loading')}</p>
      </div>
    )
  }

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={category.key}
        role="listbox"
        className="w-full flex flex-col gap-1"
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        exit={{ opacity: 0, x: -20 }}
        transition={{ duration: 0.3, ease: [0.25, 1, 0.5, 1] }}
        style={{ y: scrollY }}
      >
        {category.items.map((item, i) => (
          <PlaylistItemWrapper
            key={item.id}
            item={item}
            index={i}
            activeItemIndex={activeItemIndex}
            scrollY={scrollY}
            onSelectItem={onSelectItem}
            onOpenItem={onOpenItem}
          />
        ))}
      </motion.div>
    </AnimatePresence>
  )
}
