// src/App.tsx
import { useState } from 'react'
import { MusicProvider } from './contexts/MusicContext'
import { LandingPage, REVEAL_MS } from './components/LandingPage'
import { MTBShell } from './components/mtb/MTBShell'
import { playSound, setMuffled } from './effects/soundEngine'
import './lib/i18n'

export default function App() {
  const [view, setView] = useState<'landing' | 'reveal' | 'shell'>('landing')
  const [landingHovered, setLandingHovered] = useState(false)

  const handleOpen = () => {
    playSound('boot_up')
    setMuffled(false) // Open master filter
    setLandingHovered(false)
    setView('reveal')
    setTimeout(() => {
      setView('shell')
    }, REVEAL_MS)
  }

  return (
    <MusicProvider>
      <div className="relative w-full h-full">
        <MTBShell
          onExit={() => {
            setMuffled(true) // Muffle master filter when returning to landing page
            setView('landing')
          }}
          isActive={view === 'shell'}
        />
        {view !== 'shell' && (
          <>
            <LandingPage
              isRevealing={view === 'reveal'}
              isHovered={landingHovered}
            />
            <div
              onMouseEnter={() => view === 'landing' && setLandingHovered(true)}
              onMouseLeave={() => setLandingHovered(false)}
              onClick={handleOpen}
              className={`absolute top-0 right-0 w-64 h-64 z-[60] bg-transparent transition-all ${
                view === 'reveal' ? 'pointer-events-none' : 'pointer-events-auto cursor-pointer'
              }`}
            />
          </>
        )}
      </div>
    </MusicProvider>
  )
}

// src/App.svelte
<script lang="ts">
  import LandingPage, { REVEAL_MS } from './components/LandingPage.svelte'
  import MTBShell from './components/mtb/MTBShell.svelte'
  import { playSound, setMuffled } from './effects/soundEngine'
  import './lib/i18n.svelte'

  let view = $state<'landing' | 'reveal' | 'shell'>('landing')
  let landingHovered = $state(false)

  function handleOpen() {
    playSound('boot_up')
    setMuffled(false) // Open master filter
    landingHovered = false
    view = 'reveal'
    setTimeout(() => {
      view = 'shell'
    }, REVEAL_MS)
  }
</script>

<div class="relative w-full h-full">
  <MTBShell
    onExit={() => {
      setMuffled(true) // Muffle master filter when returning to landing page
      view = 'landing'
    }}
    isActive={view === 'shell'}
  />

  {#if view !== 'shell'}
    <LandingPage
      isRevealing={view === 'reveal'}
      isHovered={landingHovered}
    />
    
    <!-- Keyboard/mouse trigger zone for the corner peel -->
    <div
      onmouseenter={() => view === 'landing' && (landingHovered = true)}
      onmouseleave={() => landingHovered = false}
      onclick={handleOpen}
      onkeydown={(e) => e.key === 'Enter' && handleOpen()}
      class="absolute top-0 right-0 w-64 h-64 z-[60] bg-transparent transition-all {view === 'reveal' ? 'pointer-events-none' : 'pointer-events-auto cursor-pointer'}"
      role="button"
      tabindex="0"
      aria-label="Enter portfolio"
    ></div>
  {/if}
</div>
