// src/components/apps/GalagaDemo.tsx
interface Props { onClose: () => void }

export function GalagaDemo({ onClose: _onClose }: Props) {
  return (
    <div className="h-full flex items-center justify-center">
      <div className="text-center">
        <p className="text-6xl mb-4">👾</p>
        <p className="text-lg font-display font-semibold text-[var(--text-primary)] mb-2">Galaga</p>
        <p className="text-sm text-[var(--text-muted)]">Coming soon</p>
      </div>
    </div>
  )
}

// src/components/apps/GalagaDemo.svelte
<script lang="ts">
  import type { AppProps } from '@/types'
  let { onClose: _onClose }: AppProps = $props()
</script>

<div class="h-full flex items-center justify-center">
  <div class="text-center">
    <p class="text-6xl mb-4">👾</p>
    <p class="text-lg font-display font-semibold text-[var(--text-primary)] mb-2">Galaga</p>
    <p class="text-sm text-[var(--text-muted)] font-mono">Coming soon</p>
  </div>
</div>
